# ==========================
# APPLICATION
# ==========================
spring.application.name=drinkit-backend

# ==========================
# SERVER
# ==========================
server.port=${PORT:9090}

# ==========================
# MYSQL DATABASE
# ==========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA / HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ==========================
# FILE UPLOAD
# ==========================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB